/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const library = require('@fortawesome/fontawesome-svg-core');
// const FontAwesomeIcon = require('@fortawesome/react-fontawesome');
// const faHome = require('@fortawesome/free-solid-svg-icons');

// import { library } from '@fortawesome/fontawesome-svg-core';
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
// import { faHome } from '@fortawesome/free-solid-svg-icons';

// library.add(faHome);

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  javaSidebar: [{
    type: 'autogenerated',
    dirName: 'java',
    // icon: <FontAwesomeIcon icon="home" />
  }],
  scalaSidebar: [{type: 'autogenerated', dirName: 'scala'}],
  springSidebar:[{type: 'autogenerated', dirName: 'spring'}],
  blockchainSidebar: [{type: 'autogenerated', dirName: 'blockchain'}],
  flutterSidebar: [{type: 'autogenerated', dirName: 'flutter'}],
  algorithmSidebar: [{type: 'autogenerated', dirName: 'algorithm'}],
  pythonSidebar: [{type: 'autogenerated', dirName: 'python'}],
  reactiveSidebar: [{type: 'autogenerated', dirName: 'reactive'}],
  jsSidebar: [{type: 'autogenerated', dirName: 'javascript'}],
  cryptologySidebar: [{type: 'autogenerated', dirName: 'cryptology'}],
  aiSidebar: [{type: 'autogenerated', dirName: 'AI'}],
  aigcSidebar: [{type: 'autogenerated', dirName: 'AIGC'}],
  interviewSidebar: [{type: 'autogenerated', dirName: 'interview'}],

  architSidebar: [{type: 'autogenerated', dirName: 'Architecture'}],
  cheatSidebar: [{type: 'autogenerated', dirName: 'cheatSheet'}],
  csSidebar: [{type: 'autogenerated', dirName: 'computer-science'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],
  linuxSidebar: [{type: 'autogenerated', dirName: 'linux'}],
  dbSidebar: [{type: 'autogenerated', dirName: 'db'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
